language: java
sudo: required
services:
  - docker
branches:
  only:
  - master
git:
  depth: 1
after_success:
  - docker build -t appimage .
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag appimage sichyuriyy/docker-aws-travis-test:latest
  - docker push sichyuriyy/docker-aws-travis-test:latest
  - pip install --user awscli
  - eval $(aws ecr get-login --region us-east-2 --no-include-email)
  - docker tag appimage 739684674407.dkr.ecr.us-east-2.amazonaws.com/get-started:latest
  - docker push 739684674407.dkr.ecr.us-east-2.amazonaws.com/get-started:latest

