version: "3"
services:
  web:
    image: sichyuriyy/docker-aws-travis-test:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet: