version: "3"
services:
  web:
    image: 739684674407.dkr.ecr.us-east-2.amazonaws.com/get-started:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet: